services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Quellwerke\QuellwerkeBugtrackBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Installer/'

  Quellwerke\QuellwerkeBugtrackBundle\Service\EmailService:
    autowire: true
    autoconfigure: true
    public: true
